### PR TITLE
WL-3328 - rWiki pops up a warning about missing jsMaths library over and

### PR DESCRIPTION
**Pull request by nicholaswilson100**
WL-3328 - rWiki pops up a warning about missing jsMaths library over and over

Add the missing jsMaths file from 2.8 referred to 
in rwiki-tool web.xml as '/library/jsMath/jsMath.js'

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
The 2.8 codebase doesn't have this issue.  When you first go to the Wiki tool in 2.8, a box at the bottom flashes for a second or two saying 'Processing Math: DONE' then disappears.

I've also just seen WL-74 where this issue was fixed in 2.8 (by setting       <activeByDefault>false</activeByDefault> to true for jsmath in the library/pom.xml).  Should that be done as well / instead?

**Comment by ghost** [comment]
How about here?

http://nightly2.sakaiproject.org/

**Comment by buckett** [comment]
@nicholaswilson100 Yep, it looks like the jsMath codebase should be pulled in as it was done in WL-74. I'm guessing WL-74 didn't get merged across.

**Comment by nicholaswilson100** [comment]
Yes it's not a problem here: http://nightly2.sakaiproject.org/ for the 10 build. 
I've reverted adding the jsMath.js file and changed the jsmath Maven profile activeByDefault value to true (it was false) like 2.8.

**Pull request merged**
