### PR TITLE
WL-3974: Remove Show Hide All Preferred Libraries links

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Linked to https://github.com/ox-it/wl-citations/pull/75

**Comment by buckett** [comment]
How is this related to ox-it/wl-citations#75 ?

**Comment by nicholaswilson100** [comment]
They are both changes on the same page and they are both in the same Jira.   Although not logically co-dependent, it's just to avoid having to create loads and loads of Jiras which is an admin pain for Adam.

**Comment by buckett** [comment]
Ah sorry I see your comment on the other issue to that effect.

**Pull request merged**
