### PR TITLE
WL-3316 : Add css for new Quick Links drop down

### PR DESCRIPTION
**Pull request by nicholaswilson100**
And fix bug for My Sites css so that it appears beneath the link..

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Linked to https://github.com/ox-it/wl-portal/pull/30

**Comment by buckett** [comment]
Indentation is space in this file I think.

**Comment by buckett** [comment]
Still waiting on indentation changes on this one.

**Comment by nicholaswilson100** [comment]
Sorry, slipped off the radar this one...

**Comment by buckett** [comment]
No worries.

**Pull request merged**
