### PR TITLE
Added Bodleian Japanese Library (BJLBL) to library codes list. 

### PR DESCRIPTION
**Pull request by ostephens**
Also removed console logging from this file

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Cool yeah console.log isn't supported in IE10 I don't think

**Comment by nicholaswilson100** [comment]
At some point  these libraries need to be put into a JSON file and got them from there as this code isn't allowed to contain any hardcoded Oxford specific stuff

**Comment by nicholaswilson100** [comment]
This is the file they need to be added to:

**Comment by ostephens** [comment]
File reference didn't come through - can you point me at it?

**Comment by nicholaswilson100** [comment]
Silly github won't let me upload

**Comment by nicholaswilson100** [comment]
{"managingLibraries": 
 [
       {"id": "ANNCL", "name": "St Anne's College Library"},
       {"id": "ANTCL", "name": "St Antony's College Library"},
       {"id": "ANTRE", "name": "Russian & East Eur. Library"},
       {"id": "ASCCL", "name": "All Souls College Library"},
       {"id": "ASHDL", "name": "Ashmolean Museum Library"},
       {"id": "BALDL", "name": "Balfour Lib (Pitt Rivers Mus)"},
       {"id": "BLFCL", "name": "Blackfriars Library"},
       {"id": "BLLCL", "name": "Balliol College Library"},
       {"id": "BNCCL", "name": "Brasenose College Library"},
       {"id": "BJLBL", "name": "Bodleian Japanese Library"},
       {"id": "BODBL", "name": "Bodleian Library"},
       {"id": "BOLBL", "name": "Bodleian Library Lending"},
       {"id": "CCLBL", "name": "China Centre: KB Chen Library"},
       {"id": "CEDBL", "name": "Continuing Education Library"},
       {"id": "CSLBL", "name": "Chinese Studies Library"},
       {"id": "EDUBL", "name": "Education Library"},
       {"id": "EFLBL", "name": "English Faculty Library"},
       {"id": "HCLBL", "name": "Health Care - Cairns"},
       {"id": "HCLKC", "name": "Health Care - Knowledge Cent"},
       {"id": "HEBBL", "name": "Hebrew and Jewish Studies Lib"},
       {"id": "HFLBL", "name": "Bodleian History Faculty Lib"},
       {"id": "INDBL", "name": "Indian Institute Library"},
       {"id": "LACBL", "name": "Latin American Centre Library"},
       {"id": "LAWBL", "name": "Bodleian Law Library"},
       {"id": "MTHBL", "name": "Mathematical Inst Gerrans Coll"},
       {"id": "MUSBL", "name": "Music Faculty Library"},
       {"id": "OILBL", "name": "Oriental Institute Library"},
       {"id": "PHIBL", "name": "Philosophy Faculty Library"},
       {"id": "PLSBL", "name": "Sherardian Library"},
       {"id": "PTFBL", "name": "Philosophy & Theology Fac Lib"},
       {"id": "RHOBL", "name": "Rhodes House Library"},
       {"id": "RSLBL", "name": "Radcliffe Science Library"},
       {"id": "SACBL", "name": "Sackler Library"},
       {"id": "SBSBL", "name": "Said Business School Library"},
       {"id": "SCABL", "name": "Soc and Cultural Anth Library"},
       {"id": "SSLBL", "name": "Social Science Library"},
       {"id": "STFBL", "name": "Bodleian Staff Library"},
       {"id": "TASBL", "name": "Taylor Slavonic Library"},
       {"id": "TAYBL", "name": "Taylor Institution Library"},
       {"id": "THEBL", "name": "Theology Faculty Library"},
       {"id": "VHLBL", "name": "Vere Harmsworth Library"},
       {"id": "WELBL", "name": "Wellcome Unit Library"},
       {"id": "ZOOBL", "name": "Alexander Library"},
       {"id": "ARABL", "name": "Accessible Resources Unit"},
       {"id": "BODCA", "name": "Copyright Receipt Office"},
       {"id": "BODEA", "name": "English Accessions"},
       {"id": "BODFA", "name": "Acquisitions Services"},
       {"id": "BODHA", "name": "Hispanic Accessions"},
       {"id": "BODOA", "name": "Oriental Accessions"},
       {"id": "BODSA", "name": "Slavonic Accessions"},
       {"id": "BODXA", "name": "Music Accessions"},
       {"id": "GOOGL", "name": "Google Resources"},
       {"id": "SYSBL", "name": "Systems Team Library"},
       {"id": "BODTS", "name": "Temp Sub Library"},
       {"id": "EFLCD", "name": "English Fac Lib Issue Desk"},
       {"id": "HCLCD", "name": "Health Care - Cairns Main Desk"},
       {"id": "HCLCK", "name": "Health Care - Knowledge Centre"},
       {"id": "HEBCD", "name": "Hebrew & Jewish St. Main Desk"},
       {"id": "HFLCD", "name": "Bodleian History Lib LCam Desk"},
       {"id": "OILCD", "name": "Oriental Inst. Lib. Main Desk"},
       {"id": "PTFCD", "name": "Phil & Theol Fac Lib Main Desk"},
       {"id": "RSLCD", "name": "RSL Main Desk"},
       {"id": "TASCD", "name": "Taylor Slavonic Main Desk"},
       {"id": "TAYCD", "name": "Taylor Inst Main Desk"},
       {"id": "CAMCL", "name": "Campion Hall Library"},
       {"id": "CARDL", "name": "Careers Service Res Centre"},
       {"id": "CATCL", "name": "St Catherine's Coll Library"},
       {"id": "CCCCL", "name": "Corpus Christi Coll Library"},
       {"id": "CHCCL", "name": "Christ Church - Main Library"},
       {"id": "CMSNU", "name": "Mission Studies Library"},
       {"id": "COMDL", "name": "Computer Science Library"},
       {"id": "COSNU", "name": "Oxfordshire History Centre"},
       {"id": "DOMDL", "name": "Dept of Materials Library"},
       {"id": "EARDL", "name": "Earth Sciences Library"},
       {"id": "ENGDL", "name": "Engineering Science Library"},
       {"id": "EXECL", "name": "Exeter College Library"},
       {"id": "GRFNU", "name": "Greyfriars Franciscan Library"},
       {"id": "GTCCL", "name": "Green Templeton Coll Library"},
       {"id": "HEBNU", "name": "Hebrew and Jewish Studies Lib"},
       {"id": "HERCL", "name": "Hertford College Library"},
       {"id": "HINNU", "name": "Hindu Studies Library"},
       {"id": "HMCCL", "name": "Harris Manchester College Lib"},
       {"id": "HSCDL", "name": "Human Sciences Library"},
       {"id": "HUGCL", "name": "St Hugh's College Library"},
       {"id": "ICLNU", "name": "Instituto Camoes Library"},
       {"id": "IESNU", "name": "Institute for Energy Studies"},
       {"id": "ISLNU", "name": "Islamic Studies Library"},
       {"id": "JESCL", "name": "Jesus College Library"},
       {"id": "KEBCL", "name": "Keble College Library"},
       {"id": "KELCL", "name": "Kellogg College Library"},
       {"id": "LANDL", "name": "Language Centre Library"},
       {"id": "LCRCL", "name": "Linacre College Library"},
       {"id": "LINCL", "name": "Lincoln College Library"},
       {"id": "LMHCL", "name": "Lady Margaret Hall Library"},
       {"id": "MAGCH", "name": "Magdalen Coll Chantry Library"},
       {"id": "MAGCL", "name": "Magdalen College Library"},
       {"id": "MAGCD", "name": "Magdalen College Circ Desk"},
       {"id": "MATDL", "name": "Mathematical Inst Library"},
       {"id": "MECDL", "name": "Middle East Centre Library"},
       {"id": "MERCL", "name": "Merton College Library"},
       {"id": "MFONU", "name": "Maison Francaise Library"},
       {"id": "MHSDL", "name": "Museum of Hist of Sci Library"},
       {"id": "MNSCL", "name": "Mansfield College Library"},
       {"id": "NEWCL", "name": "New College Library"},
       {"id": "NUFCL", "name": "Nuffield College Library"},
       {"id": "OIIDL", "name": "Oxford Internet Inst Library"},
       {"id": "OLIDL", "name": "Oxford Learning Inst Library"},
       {"id": "ORLCL", "name": "Oriel College Library"},
       {"id": "OUMDL", "name": "Museum of Nat Hist Library"},
       {"id": "OUSNU", "name": "Oxford Union Society Library"},
       {"id": "PEMCL", "name": "Pembroke College Library"},
       {"id": "PHLNU", "name": "Pusey House Library"},
       {"id": "QUECL", "name": "Queen's College Library"},
       {"id": "REGCL", "name": "Regent's Park College Library"},
       {"id": "RUSDL", "name": "Ruskin School Library"},
       {"id": "SEHCL", "name": "St Edmund Hall Library"},
       {"id": "SOMCL", "name": "Somerville College Library"},
       {"id": "SPCCL", "name": "St Peter's College Library"},
       {"id": "STADL", "name": "Statistics Library"},
       {"id": "STBCL", "name": "St Benet's Hall Library"},
       {"id": "STJCL", "name": "St John's College Library"},
       {"id": "STXCL", "name": "St Cross College Library"},
       {"id": "SYSSL", "name": "Systems Team Sub-Library"},
       {"id": "CEUHL", "name": "Cancer Epidemiology Unit"},
       {"id": "OPTHL", "name": "Nuffield Lab of Opthalmology"},
       {"id": "TRICL", "name": "Trinity College Library"},
       {"id": "UNVCL", "name": "University College Library"},
       {"id": "WADCL", "name": "Wadham College Library"},
       {"id": "WOLCL", "name": "Wolfson College Library"},
       {"id": "WORCL", "name": "Worcester College Library"}
    ]
}

**Comment by nicholaswilson100** [comment]
It's named managingLibraries.json and it's hosted on Weblearn (in a site called 'Citations Admin'), here (but I don't think you'll have access):

https://weblearn.ox.ac.uk/access/content/group/citationsAdmin/managingLibraries/managingLibraries.json

**Comment by nicholaswilson100** [comment]
This file does not have the Bodleian Japanese library in it. And I was thinking each library row would have an extra "site" key.

**Comment by ostephens** [comment]
"BJLBL":"http://www.bodleian.ox.ac.uk/bjl" is the Japanese library. Should we move discussion of this outside this specific PR, or OK to go through this here?

**Comment by nicholaswilson100** [comment]
whereever you like :)

**Comment by ostephens** [comment]
OK - I'll move over to email to discuss this. This PR request stands, but noted that we want to move the list of lib codes into external file in a future PR

**Comment by nicholaswilson100** [comment]
ok I've created a ticket

**Comment by nicholaswilson100** [comment]
Sorry just re-doing this merge

**Pull request merged**
