### PR TITLE
WL-3950: Very basic availability table - Owen's new files

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Linked to https://github.com/ox-it/wl-citations/pull/56

**Comment by nicholaswilson100** [comment]
Linked to https://github.com/ox-it/wl-sirlouie/pull/5

**Comment by buckett** [comment]
Is this meant for review, isn't it Owen's code?

**Comment by nicholaswilson100** [comment]
Yes it's Owen's so not necessarily needed to be reviewed.

**Comment by buckett** [comment]
I didn't mean it shouldn't be reviewed, I just meant that wouldn't it be better if you took up any issues with it directly with Owen.

We're still going to be running this code in production and any supporting it so it should be reviewed.

**Comment by nicholaswilson100** [comment]
Ah right yes I've been speaking to him about these files ...

**Pull request merged**
