### PR TITLE
WL-3344 Remove Tests & Quizes from CK Browser

### PR DESCRIPTION
**Pull request by ghost**
I've not tested this locally since I'm WFH but it looks like it should work :-)

### CODE REVIEW

**Comment by buckett** [comment]
Could you just surround the blocks of code in if() checks then we can push this change back (and we just have a one line change which is if it's enabled.)

**Comment by ghost** [comment]
Sure thing

**Comment by buckett** [comment]
The paths are for FCKEditor, does CKEditor still use the file manager from FCKEditor?

**Comment by ghost** [comment]
Haha yep :D

**Comment by buckett** [comment]
But it does seem to be used, on jenkins when I use the filepicker from CKEditor the URLs I see are:

```
 /library/editor/FCKeditor/editor/filemanager/browser/default/browser.html
```

[trimmed for sanity]

**Comment by ghost** [comment]
Exactly, it uses a connector to get the files e.g.

```
https://jenkins.oucs.ox.ac.uk:40443/sakai-fck-connector/web/editor/filemanager/browser/default/connectors/jsp/connector/group/3be7ed8b-d06e-4a3a-85c0-e1afcef81b25/
```

**Comment by ghost** [comment]
Ok how about this?

**Comment by ghost** [comment]
There is a FCKConfig but it's not in scope at all in either file, it seems like the connector is being used partially for config anyway.

**Comment by buckett** [comment]
In your earlier commit there were 2 sections commented out, is this no longer needed.

**Comment by ghost** [comment]
Yeah, it turns out the first section is actually for Assignments.

**Comment by buckett** [comment]
:+1: Cool.

**Pull request merged**
